sudo: required
services:
  - docker
before_install:
  - docker build -t pankajchoudhary/react-test -f ./client/Dev.Dockerfile ./client
script:
  - docker run pankajchoudhary/react-test npm run test -- --coverage
after_success:
  - docker build -t pankajchoudhary/multi-nginx  ./nginx
  - docker build -t pankajchoudhary/multi-server  ./server
  - docker build -t pankajchoudhary/multi-client  ./client
  - docker build -t pankajchoudhary/multi-worker  ./worker
deploy:
  - provider:  script
    script: bash docker_push.sh
    on:
      branch:
        master
  - provider: elasticbeanstalk
    access_key_id: 
      secure: "${AWS_ACCESS_KEY}"
    secret_access_key:
      secure: "${AWS_SECRET_KEY}"
    region: "ap-south-1"  
    app: "multi-container"
    env: "MultiContainer-env"
    bucket_name: "elasticbeanstalk-ap-south-1-806107407018"
    on:
      branch: master