sudo: required
services:
  - docker
before_install:
  - docker build -t react-app .
script:
  - docker run react-app npm run test -- --coverage
after_success:
  - docker tag react-app:latest 806107407018.dkr.ecr.ap-south-1.amazonaws.com/react-app:latest
deploy:
  - provider:  script
    script: bash docker_push.sh
    on:
      branch:
        master