sudo: required
services:
  - docker
before_install:
  - docker build -t react-app -f Dev.Dockerfile .
script:
  - docker run react-app npm run test -- --coverage
deploy:
  - provider:  script
    script: bash docker_push.sh
    on:
      branch:
        master